
url: "https://lichess.org/"  # lichess base URL
good_luck_messages: # messages sent to chat when game begins
  - "good luck"
good_game_message: "good game" # message sent to chat when game finishes

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "stockfish"        # binary name of the engine to use
  protocol: "uci"            # "uci" or "xboard"

  polyglot:
    enabled: false           # activate polyglot book
    books:
      - "engines/books/default.bin"
      - "engines/books/Book.bin"
      - "engines/books/Elo2400.bin"
      - "engines/books/final-book.bin"
      - "engines/books/komodo.bin"
      - "engines/books/gavibook.bin"
      - "engines/books/gm2600.bin"
      - "engines/books/Performance.bin"
    max_depth: 8             # half move max depth
    min_weight: 1             # selects move with highest weight but not below this value
    random: true             # selects move randomly; otherwise select the best but not below the min_weight
  uci_options:               # arbitrary UCI options passed to the engine
    Move Overhead: 100       # increase if your bot flags games too often
    Ponder: true
    Slow Mover: 30           # slow mover
    Threads: 4               # max CPU threads the engine can use
    Hash: 256                # max memory (in megabytes) the engine can allocate
    Skill Level: 20          #
  silence_stderr: false      # some engines (yes you, leela) are very noisy
max_concurrent_games: 1      # number of games to play simultaneously
abort_time: 20               # time to abort a game in seconds when there is no activity

challenge:                   # incoming challenges
  sort_by: "first"            # possible values: "best", "first"
  accept_bot: true          # accepts challenges coming from other bots
  variants:                  # chess variants to accept (http://lichess.org/variant)
    - standard
    - fromPosition
#   - antichess
#   - atomic
#   - chess960
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:             # time controls to accept
#   - ultraBullet
    - bullet
#   - blitz
#   - rapid
#   - classical
#   - correspondence
  modes:                     # game modes to accept
#   - casual                 # unrated games
    - rated                  # rated games - must comment if the engine doesn't try to win
